#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for School in School; do
    if [[ "$School" == $(("wc -l" == '10')) ]]
    then
    break
    fi
    echo "Best $School"
    done
