#!/usr/bin/env bash
# display bad luck and good luck
bs=0
while [ $bs -lt 10 ]
do
      echo "Best School"
      (( bs++ ))
      if [ $bs == 4]
      then
	  echo "bad luck"
      elif [ $bs == 8 ]
      then
	  echo "good luck"
      else
	  true
      fi
done
