#!/usr/bin/env bash
# display numbers and countries after a certain line
n=1
while [ $n -le 20 ]
do
	echo $n
	(( n++ ))
	case $n in
	4)
	echo "bad luck from China"
	;;
	9)
	echo "bad luck from Japan"
	;;
	17)
	echo "bad luck from Italy"
	;;
esac
