#!/usr/bin/env bash
# lookin for a file and printing answers for each condition
srch=$(find . -name school)

if [ $srch ]
then
    echo "school file does not exist"
else
    echo "school file exists"
fi
if [ -s $srch ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
fi
if [ -f $srch ]
    then
	echo "school is a regular file"
fi

