#!/usr/bin/env bash
# lookin for a file and printing answers for each condition
srch=$(ls | grep -q school)

if [ $srch == 0 ]
then
    echo "school file exists"
    if [ -s $srch ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f $srch ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
