#!/usr/bin/env bash
# displays a list of currently running processes
# must show all processes for all users in a user-oriented format and hierarchy
top | awk '{print $f2"\t"$f1"\t"$f3"\t"$f4"\t"$f5"\t"$f6"\t"$f7"\t"$f8"\t"F9"\t"F10"\t"F11}' | sort -n
